New branch: Added index.html, style.css and README.md files
JbirdL86/Trial-Review pull request #1
Opened 2021-06-02 19:54 UTC by JbirdL86

2021-06-02 20:28 UTC, JbirdL86 reviewed
Hi @JbirdL86!

Great Job so far! 

I can still see some issues you need to work on in order to merge this branches but no worries, you'll fix them in no time!

### **Required Changes** recycle
____________________________________________________________________________

- All lintern errors have to be cleared out so you can merge branches, I suggest to follow the linters hints and clear the errors.
- Semantics are very important for the DOM, please go ahead and change labels to their equivalent with semantics.

2021-06-03 01:22 UTC, Spayco requested changes
Hi @JbirdL86, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

Your review could use some improvements, please create a new one and double-check that you're following this list:
- GitHub features
  - it's best to utilize the "Review changes" feature from GitHub
  - (from the lesson page) it's required to find at least 2 issues in the code
  - please include those changes using [inline comments](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request)
- Communication: 
  - kindly phrase the comments politely, as suggestions instead of orders. For example:
     * This is a polite suggestion: *"I think it would be better to use semantic tags"*
     * This reads as an order: *"Use semantic tags"*
  - please always include an explanation, a "why", for each requested change. For example:
     * This is a well explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*
     * This request lacks a "why": *Why don't you use an article tag here instead of a div?*
  
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 04:23 UTC, JbirdL86 reviewed
Hi, @JbirdL86!

Great job so far!
There are still some changes you need to work on to go to the next project but don't worry, you are almost there!
### **Requiered changes** :recycle: 
____________________________________________________________________________

- Keeping your code clean is always a good practice I suggest clearing all the empty lines and use the correct spacing.
- It is necessary to clean all the linterns errors so you can merge branches, I suggest following the linter's hints and clear the errors.

2021-06-03 04:23 UTC, JbirdL86 commented on index.html
> +<html>
I suggest adding the language property. browsers use the lang property to identify how the document will be read.

2021-06-03 04:23 UTC, JbirdL86 commented on index.html
> +    >
I think indentation would help your code more readable and organized.

2021-06-03 04:23 UTC, JbirdL86 commented on style.css
> +  }
It's always a good practice to keep the code clean and organized, I suggest using the standard indentation rules and deleting empty lines.

2021-06-03 05:16 UTC, euqueme approved these changes
Hi @ArthurGC :lollipop: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing all of the requested changes. Awesome job!  :100: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Let's edit the Pull Request comment and write a short summary of what this project is all about
- Let's fix these small issues in your README file, I put them in the comments below :point_down: 

That's it! :raised_hands: 

Please :pray: do the changes :technologist: (or not) and move on to the next project :runner:  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

#### PROJECT STATUS: APPROVED :heavy_check_mark:

2021-06-03 05:16 UTC, euqueme commented on README.md
> +> HEllo-Microverse is a project where we get to review a pull request of our own just to practice how to do reviews on a pull request.
[OPTIONAL] This is not the Hello-Microverse project this is the Trial-Review one let's change it in this line

2021-06-03 05:16 UTC, euqueme commented on README.md
> +![screenshot](https://rawcdn.githack.com/JbirdL86/Hello-World/6b13fe40173fca2382ccd5af586136d93779e768/index.html)
[OPTIONAL] Let's fix the screenshot as it seems to be broken.

2021-06-03 05:16 UTC, euqueme commented on README.md
> +[Live Demo Link](https://rawcdn.githack.com/JbirdL86/Hello-Microverse/67410abe5d2786e9eaa774109edb5c6a6838c148/index.html
[OPTIONAL] There's a closing parenthesis missing in this line

2021-06-03 06:07 UTC, merged